name: pymebm
channels:
  - conda-forge
dependencies:
  - python=3.12.*
  # Required for full project functionality (dont remove)
  - pytest
  # Examples (remove and add as needed)
  - numpy
  - scipy
  - matplotlib
  - numba
